import { EquationSolver } from '../symbolic/equation';
import { ExpressionParser } from '../parser';
import { ASTNormalizer } from '../parser/normalizer';

describe('CORE CALCULUS SUBPHASE 2C - Radical & Absolute Value Equations', () => {
  const parser = new ExpressionParser();
  const normalizer = new ASTNormalizer();
  const solver = new EquationSolver();

  const parseToAST = (expr: string) => normalizer.normalize(parser.parse(expr));

  describe('1. Absolute Value Equations', () => {
    it('solves simple absolute value: |x - 3| = 5', () => {
      const ast = parseToAST('abs(x - 3) = 5');
      const { finalSolutions } = solver.solve(ast, 'x');
      const vals = finalSolutions.map(s => parseFloat((s.value as any).value));
      
      expect(vals.length).toBe(2);
      expect(vals).toContain(8);  // x - 3 = 5 => x = 8
      expect(vals).toContain(-2); // -(x - 3) = 5 => -x + 3 = 5 => x = -2
    });

    it('rejects extraneous roots from negative absolute equality: |x| = -2', () => {
      const ast = parseToAST('abs(x) = -2');
      const { finalSolutions, rejectedSolutions } = solver.solve(ast, 'x');
      
      expect(finalSolutions.length).toBe(0);
      expect(rejectedSolutions.length).toBe(2); // Branches x=-2 and -x=-2 (x=2) are both evaluated and rejected
    });

    it('solves nested absolute value equations: ||x| - 2| = 1', () => {
      const ast = parseToAST('abs(abs(x) - 2) = 1');
      const { finalSolutions } = solver.solve(ast, 'x');
      const vals = finalSolutions.map(s => parseFloat((s.value as any).value));
      
      expect(vals.length).toBe(4);
      expect(vals).toContain(3);
      expect(vals).toContain(-3);
      expect(vals).toContain(1);
      expect(vals).toContain(-1);
    });
  });

  describe('2. Radical Equations', () => {
    it('solves simple square root equation: sqrt(x - 2) = 4', () => {
      const ast = parseToAST('sqrt(x - 2) = 4');
      const { finalSolutions } = solver.solve(ast, 'x');
      const vals = finalSolutions.map(s => parseFloat((s.value as any).value));
      
      expect(vals.length).toBe(1);
      expect(vals).toContain(18); // sqrt(16) = 4 -> x = 18
    });

    it('rejects extraneous roots generated by squaring: sqrt(x) = -3', () => {
      const ast = parseToAST('sqrt(x) = -3');
      const { finalSolutions, rejectedSolutions } = solver.solve(ast, 'x');
      
      expect(finalSolutions.length).toBe(0);
      // It generates x = 9 by squaring, but original is sqrt(9) = 3 != -3, so it rejects it.
      expect(rejectedSolutions.length).toBe(1);
      expect(parseFloat((rejectedSolutions[0].value as any).value)).toBe(9);
    });

    it('handles roots inside equations: x - sqrt(x) = 6', () => {
      const ast = parseToAST('x - sqrt(x) = 6');
      const { finalSolutions, rejectedSolutions } = solver.solve(ast, 'x');
      const vals = finalSolutions.map(s => parseFloat((s.value as any).value));
      
      // sqrt(x) = x - 6 => x = x^2 - 12x + 36 => x^2 - 13x + 36 = 0 => (x-9)(x-4)=0. 
      // check 9: 9 - 3 = 6 (valid). check 4: 4 - 2 = 2 != 6 (extraneous).
      expect(vals.length).toBe(1);
      expect(vals).toContain(9);
      expect(rejectedSolutions.length).toBe(1);
      expect(parseFloat((rejectedSolutions[0].value as any).value)).toBe(4);
    });
  });
});
